version: "3"

services:
  frontend:
    image: spygram/todo-fe:latest
    build: ./frontend
    container_name: react-app
    ports:
      - "3100:3100"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-networks

  backend:
    image: spygram/todo-be:latest
    build: ./backend
    container_name: node-app
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - database
    networks:
      - mern-networks

  database:
    image: mongo:4.0.5-xenial
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - /home/sd/mongobkup:/data/db
    networks:
      - mern-networks

networks:
  mern-networks:
    driver: bridge
